-- Compatible form-schema corrections: preserve legacy codes, values and file links.
UPDATE app_information_templates SET fields_json=json_insert(json_insert(json_insert(json_set(fields_json,'$[8].label','Tadbir sanasi','$[14].label','Sertifikat fayli'),'$[#]',json('{"code":"tadbir_joyi","label":"Tadbir o‘tkazilgan joy","type":"text","required":false}')),'$[#]',json('{"code":"sertifikat_nomi","label":"Sertifikat nomi","type":"text","required":false}')),'$[#]',json('{"code":"sertifikat_darajasi","label":"Sertifikat darajasi","type":"text","required":false}')),
  presentation_json=json_set(presentation_json,'$.tableColumns',json('["malumot_turi","nomi","sana_joy","tadbir_joyi","tashkilot","tashkilotchi","qatnashchilar","ishtirokchilar_soni","sport_musobaqasi","yoshlar_uchrashuvi","iqtidorli_yosh","iqtidor_yonalishi","yutuq","til","sertifikat_nomi","sertifikat_darajasi","sertifikat_nomi_darajasi","amal_qilish_muddati","foto_hujjat"]'),'$.tabs[0].columns',json('["nomi","sana_joy","tadbir_joyi","tashkilot","tashkilotchi","qatnashchilar","ishtirokchilar_soni","natija_orin","foto_hujjat"]'),'$.tabs[1].columns',json('["sport_musobaqasi","nomi","sana_joy","tadbir_joyi","tashkilot","tashkilotchi","qatnashchilar","ishtirokchilar_soni","natija_orin","foto_hujjat"]'),'$.tabs[2].columns',json('["yoshlar_uchrashuvi","nomi","sana_joy","tadbir_joyi","tashkilot","tashkilotchi","qatnashchilar","ishtirokchilar_soni","natija_orin","foto_hujjat"]'),'$.tabs[3].columns',json('["iqtidorli_yosh","tashkilot","iqtidor_yonalishi","yutuq","til","sertifikat_nomi","sertifikat_darajasi","sertifikat_nomi_darajasi","amal_qilish_muddati","foto_hujjat"]')),version=version+1
WHERE code='SRC_SPORTS_YOUTH_SPORTS_YOUTH_EVENTS';
--> statement-breakpoint
UPDATE app_information_templates SET fields_json=json_insert(json_insert(json_set(fields_json,'$[26].label','Davr sanasi (avvalgi yozuv)','$[26].help','Avval kiritilgan sana. Boshlanish va tugashni alohida maydonlarda aniqlashtiring.'),'$[#]',json('{"code":"boshlanish_sanasi","label":"Boshlanish sanasi","type":"date","required":false}')),'$[#]',json('{"code":"tugash_sanasi","label":"Tugash sanasi","type":"date","required":false}')),
  presentation_json=json_set(presentation_json,'$.tableColumns',json('["ish_yonalishi","yol","ishlar","ajratilgan_mablag","sarflangan_mablag","reja_hajmi","amal_hajmi","ijro_foizi","bajaruvchi","sana","tasdiqlovchi_hujjat"]'),'$.tabs[1].columns',json('["ish_yonalishi","yol","ishlar","ajratilgan_mablag","sarflangan_mablag","reja_hajmi","amal_hajmi","ijro_foizi","bajaruvchi","sana","tasdiqlovchi_hujjat"]'),'$.tabs[2].columns',json('["ish_yonalishi","yol","ishlar","ajratilgan_mablag","sarflangan_mablag","reja_hajmi","amal_hajmi","ijro_foizi","bajaruvchi","sana","tasdiqlovchi_hujjat","boshlanish_sanasi","tugash_sanasi"]'),'$.tabs[3].columns',json('["ish_yonalishi","yol","ishlar","ajratilgan_mablag","sarflangan_mablag","reja_hajmi","amal_hajmi","ijro_foizi","bajaruvchi","sana","tasdiqlovchi_hujjat"]')),version=version+1
WHERE code='SRC_MAINTENANCE_REPAIR_MAINTENANCE_WORKS';
--> statement-breakpoint
UPDATE app_information_templates SET fields_json=json_insert(json_insert(json_set(fields_json,'$[13].label','Davr sanasi (avvalgi yozuv)','$[13].help','Avval kiritilgan sana. Boshlanish va tugashni alohida maydonlarda aniqlashtiring.'),'$[#]',json('{"code":"boshlanish_sanasi","label":"Boshlanish sanasi","type":"date","required":false}')),'$[#]',json('{"code":"tugash_sanasi","label":"Tugash sanasi","type":"date","required":false}')),
  presentation_json=json_set(presentation_json,'$.tableColumns',json('["loyiha","monitoring","lot","komponent","loyiha_id","xmi","loyiha_nomi","kredit_grant","umumiy_qiymat","ozlashtirilgan_mablag","obekt","pudratchi_konsultant","fizik_moliyaviy_ijro","boshlanish_tugash","boshlanish_sanasi","tugash_sanasi","muammo","missiya_natijasi","keyingi_qadam"]')),version=version+1
WHERE code='SRC_INVESTMENTS_PPP_IFI_PROJECTS';
--> statement-breakpoint
UPDATE app_information_templates SET fields_json=json_insert(json_insert(json_insert(json_set(fields_json,'$[5].label','Davr sanasi (avvalgi yozuv)','$[5].help','Avval kiritilgan sana. Boshlanish va tugashni alohida maydonlarda aniqlashtiring.','$[9].label','Sertifikat fayli (avvalgi maydon)'),'$[#]',json('{"code":"boshlanish_sanasi","label":"Boshlanish sanasi","type":"date","required":false}')),'$[#]',json('{"code":"tugash_sanasi","label":"Tugash sanasi","type":"date","required":false}')),'$[#]',json('{"code":"sertifikat_raqami_matni","label":"Sertifikat raqami","type":"text","required":false}')),
  presentation_json=json_set(presentation_json,'$.tableColumns',json('["xodim","malaka_yonalishi","lavozim","oquv_kurs","tashkilotchi","boshlanish_tugash","boshlanish_sanasi","tugash_sanasi","soat","moliyalashtirish","natija","sertifikat_raqami_matni","sertifikat_raqami","amal_qilish_muddati","fayl","keyingi_oquv_ehtiyoji"]')),version=version+1
WHERE code='SRC_HUMAN_RESOURCES_TRAINING_CERTIFICATES';
--> statement-breakpoint
UPDATE app_information_templates SET fields_json=json_insert(json_insert(json_set(fields_json,'$[7].label','Davr sanasi (avvalgi yozuv)','$[7].help','Avval kiritilgan sana. Boshlanish va tugashni alohida maydonlarda aniqlashtiring.'),'$[#]',json('{"code":"boshlanish_sanasi","label":"Boshlanish sanasi","type":"date","required":false}')),'$[#]',json('{"code":"tugash_sanasi","label":"Tugash sanasi","type":"date","required":false}')),
  presentation_json=json_set(presentation_json,'$.tableColumns',json('["xodim","davlat","maqsad","kun","keyingi_qadam","safar_id","shahar_tashkilot","boshlanish_tugash","boshlanish_sanasi","tugash_sanasi","buyruq","delegasiya","xarajat","uchrashuvlar","erishilgan_natija","hisobot","masul","muddat"]')),version=version+1
WHERE code='SRC_HUMAN_RESOURCES_FOREIGN_BUSINESS_TRIPS';
--> statement-breakpoint
