/**
 * Client-side shapes of the main API payloads, shared by the dashboard, task and
 * meeting modals and Excel export (previously declared three times).
 */
export type ClientPermissionSet = {
  viewScope: "all" | "subtree" | "department" | "own";
  assignScope: "all" | "subtree" | "department" | "none";
  informationScope?: "all" | "subtree" | "organization" | "department" | "own";
  canEnterInformation?: boolean;
  canSubmitInformation?: boolean;
  canVerifyInformation?: boolean;
  canApproveInformation?: boolean;
  canCreateTask: boolean;
  canCreateMeeting: boolean;
  canExport: boolean;
  canManageOrganization: boolean;
  canManageRoles: boolean;
  canConfigure: boolean;
  canViewAudit: boolean;
  canUpdateAnyTask: boolean;
  canManageReports: boolean;
  canManageInformation: boolean;
  canViewRestrictedInformation: boolean;
};
export type ClientActor = {
  id: number;
  name: string;
  email: string;
  position: string;
  departmentId: number | null;
  department: string;
  organizationId: number | null;
  organization: string;
  organizationType: string | null;
  managerId: number | null;
  roleId: number;
  roleCode: string;
  roleName: string;
  roleLevel: number;
  username: string | null;
  mustChangePassword: boolean;
  permissions: ClientPermissionSet;
};
export type ClientEmployee = {
  id: number;
  name: string;
  email: string;
  position: string;
  fullNameCyrillic: string | null;
  birthDate: string | null;
  internalExtension: string | null;
  mobilePhone: string | null;
  sourceEmployeeNumber: number | null;
  sourceRow: number | null;
  departmentId: number | null;
  department: string;
  organizationId: number | null;
  organization: string;
  organizationType: string | null;
  managerId: number | null;
  roleId: number;
  roleCode: string;
  roleName: string;
  roleLevel: number;
  active: boolean;
  telegramLinked: boolean;
  telegramUsername: string | null;
  username: string | null;
  loginConfigured: boolean;
};
export type ClientAssignment = {
  id: number;
  employeeId: number;
  name: string;
  position: string;
  role: string;
  department: string;
  status: string;
  progress: number;
};
export type ClientRouteStep = {
  id: number;
  parentRouteId: number | null;
  fromEmployeeId: number | null;
  fromName: string;
  fromRole: string;
  toEmployeeId: number;
  toName: string;
  toRole: string;
  action: string;
  note: string;
  createdAt: string;
};
export type ClientAttachment = { id: number; fileName: string; contentType: string | null; size: number; uploadedByEmployeeId: number; createdAt: string };
export type ClientAudienceTarget = { targetType: "organization" | "department"; targetId: number; targetName: string; includeDescendants: boolean };
export type ClientTask = {
  id: number;
  title: string;
  description: string;
  deadlineIso: string | null;
  priority: string;
  status: string;
  progress: number;
  recurring: boolean;
  recurrence: string | null;
  notifyTelegram: boolean;
  topic: { id: number; name: string; color: string } | null;
  pinned: boolean;
  creator: { id: number; name: string; position: string };
  assignments: ClientAssignment[];
  audiences: ClientAudienceTarget[];
  claimableByActor: boolean;
  routes: ClientRouteStep[];
  attachments: ClientAttachment[];
  createdAt: string;
  updatedAt: string;
};
export type ClientMeeting = {
  id: number;
  title: string;
  startsAt: string;
  endsAt: string | null;
  timezone: string;
  place: string;
  format: string;
  reminderMinutes: number;
  notifyTelegram: boolean;
  creatorId: number;
  creator: string;
  participants: { employeeId: number; name: string; position: string; department: string; responseStatus: string }[];
  audiences: ClientAudienceTarget[];
  createdAt: string;
};
